export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  readTime: string;
  image: string;
  content: string[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "microwave-repair-bengaluru-complete-guide",
    title: "Microwave Oven Repair in Bengaluru — Complete Diagnostic Guide 2026",
    excerpt:
      "Microwave not heating, sparking, turntable stuck, buttons dead? This complete guide explains every common microwave fault, its cause, and how our technicians diagnose and fix it — for Samsung, LG, IFB, Whirlpool, Bajaj, Godrej and Panasonic across 84+ Bengaluru neighbourhoods.",
    category: "Microwave",
    date: "2026-07-15",
    readTime: "12 min read",
    image: "/blog/microwave-maintenance.png",
    content: [
      "Your microwave oven is one of the most used appliances in your Bengaluru kitchen. When it stops working, it disrupts your entire daily routine — no quick reheating, no defrosting, no fast meals. This guide breaks down every common microwave fault, what causes it, and how our technicians diagnose and fix it.",
      "Microwave repair in Bengaluru is in high demand across all 84+ neighbourhoods we serve. From Indiranagar to Whitefield, Jayanagar to Hebbal, residents rely on same-day microwave repair services. This content is intended for Bengaluru residents who need to understand what's wrong with their microwave before calling a technician.",
      "This guide covers faults for all major microwave brands — Samsung, LG, IFB, Whirlpool, Bajaj, Godrej and Panasonic. Whether you have a solo, grill, or convection microwave, the diagnostic process is the same. The difference lies in the spare parts and internal architecture.",
      "If your microwave is under warranty, contact the brand's service centre first. If the warranty has expired or you need same-day repair, that's where we come in. Urban Service Company provides free diagnosis, genuine spare parts, and quality assured repairs across Bengaluru.",

      "Why Microwave Faults Happen",
      "Microwave ovens fail for several reasons — age, power surges, food splatter, improper use, and component wear. Understanding the root cause helps prevent recurring issues.",
      "The most common causes of microwave failure in Bengaluru are voltage fluctuations, food splatter damaging the waveguide cover, running the microwave empty, and general wear of the magnetron over time. Bengaluru's power supply can be unstable in certain areas, which stresses the microwave's internal components.",
      "Power surges damage the fuse, capacitor, and control board. Food splatter on the waveguide cover causes arcing (sparking). Running the microwave empty overheats the magnetron. And like any electronic device, components simply wear out with age and use.",

      "1. Microwave Not Heating — Magnetron Failure",
      "The magnetron is the heart of your microwave. It's the component that generates the microwaves that heat your food. When the magnetron fails, your microwave runs but doesn't heat.",
      "What causes magnetron failure? The most common causes are age (magnetrons typically last 5-10 years), power surges that damage the internal filament, running the microwave empty (no food to absorb the energy, causing the magnetron to overheat), and food splatter reaching the magnetron through a damaged waveguide cover.",
      "How do you know if the magnetron is the problem? The microwave turns on, the light works, the turntable rotates, but the food stays cold. There's no heat at all. Sometimes you might hear a louder-than-usual buzzing sound, which indicates the magnetron is struggling.",
      "Our technician diagnoses magnetron failure by testing the magnetron's resistance with a multimeter. A healthy magnetron reads about 0.5 to 1 ohm. A failed magnetron reads infinite resistance (open circuit). We also check the high-voltage diode and capacitor, as these work together with the magnetron.",
      "Magnetron replacement requires a genuine spare from the original manufacturer. We carry magnetrons for Samsung, LG, IFB, Whirlpool, Bajaj, Godrej and Panasonic. The repair takes 30-45 minutes at your home.",
      "Safety note: The high-voltage capacitor in a microwave can retain a lethal electrical current even when the microwave is unplugged. Never attempt DIY microwave repair. Our technicians are trained to safely safely drain the capacitor before working on the internal components.",

      "2. Sparking Inside the Microwave — Waveguide Cover Damage",
      "If you see sparks inside your microwave, stop using it immediately. Sparking is caused by the waveguide cover being damaged or by metal inside the cavity.",
      "The waveguide cover is a small mica sheet that sits inside the microwave cavity. It covers the opening where microwaves enter the cavity from the magnetron. Its job is to protect the magnetron from food splatter and moisture.",
      "Over time, food splatter accumulates on the waveguide cover. The food absorbs microwave energy, heats up, and eventually burns the mica sheet. A burnt waveguide cover causes sparking — which can damage the magnetron if left unchecked.",
      "Our technician inspects the waveguide cover for burning, peeling, or holes. If damaged, we replace it with a genuine mica sheet. We also inspect the magnetron for any damage caused by the sparking. This is a quick 15-20 minute repair.",
      "Prevention: Clean the microwave interior after every use. Wipe down the waveguide cover specifically — it's usually on the right side of the cavity. Don't let food splatter accumulate.",

      "3. Turntable Not Rotating — Motor or Drive Coupling",
      "If your microwave turntable has stopped rotating, food cooks unevenly — one side is hot, the other is cold. The turntable ensures even heating by rotating the food through the microwave field.",
      "The turntable system has three components: the turntable motor (located under the cavity), the drive coupling (connects the motor to the turntable), and the roller guide (the ring that supports the glass plate).",
      "The most common cause is a worn turntable motor. The motor burns out after years of continuous use. You might hear a humming sound but the turntable doesn't move. Our technician tests the motor with a multimeter — a healthy motor reads low resistance, a failed motor reads open circuit.",
      "Sometimes the drive coupling is stripped or broken. This is the plastic piece that connects the motor shaft to the turntable. It's a cheap part but needs to be the right shape for your microwave model.",
      "The roller guide can also jam if it's dirty or deformed. Cleaning the roller guide and the track it sits in often solves the issue without needing any replacement parts.",
      "Our technician replaces the motor, coupling, or roller guide as needed, using genuine spares from the original manufacturer. The repair takes 20-30 minutes.",

      "4. Buttons Not Working — Membrane Switch or Control Panel",
      "If your microwave buttons are not responding, or some buttons work while others don't, the membrane switch or control panel is faulty.",
      "The membrane switch is a thin, flexible sheet with printed circuits that sits behind the button panel. Over time, the circuits wear out from repeated pressing, moisture, and heat. When the membrane fails, the control board doesn't receive your input.",
      "In some cases, the entire control board is faulty — not just the membrane. The control board is the brain of the microwave, managing timing, power levels, and safety switches. A power surge can damage the control board.",
      "Our technician tests both the membrane switch and the control board. If the membrane is faulty, we replace it. If the control board is faulty, we repair or replace it depending on the extent of damage. Some boards can be repaired by replacing individual components; others need full replacement.",
      "Genuine control panels are brand-specific. We carry panels for Samsung, LG, IFB, Whirlpool, Bajaj, Godrej and Panasonic. The repair takes 30-45 minutes.",

      "5. Microwave Not Turning On — Fuse, Door Switch, or Thermal Fuse",
      "A microwave that won't turn on at all — no light, no display, no sound — has an electrical fault. The most common causes are a blown fuse, a faulty door switch, or a tripped thermal fuse.",
      "The main fuse protects the microwave from power surges. When it blows, the microwave is completely dead. Our technician tests the fuse with a multimeter and replaces it if blown. But we also investigate what caused the fuse to blow — a power surge, a short circuit, or a failing component. Replacing the fuse without fixing the root cause means it'll blow again.",
      "Door switches are safety devices that prevent the microwave from running when the door is open. Most microwaves have 2-3 door switches. If one fails, the microwave won't turn on — it thinks the door is open even when it's closed. Our technician tests all door switches and replaces the faulty one.",
      "The thermal fuse is a safety device that trips when the microwave overheats. It's designed to protect against fire. If your microwave overheated (perhaps from running empty or blocked ventilation), the thermal fuse trips. Our technician replaces the thermal fuse and checks for any overheating causes.",
      "These repairs take 30-45 minutes and use genuine fuses and switches from the original manufacturer.",

      "6. Uneven Heating — Weak Magnetron or Stirrer Motor",
      "If food is cooking unevenly — one side hot, the other cold — the magnetron may be weakening or the stirrer motor may be faulty.",
      "A weakening magnetron produces less microwave energy. The food still heats, but slowly and unevenly. This is a gradual failure — you might notice over weeks or months that your microwave takes longer to heat food.",
      "The stirrer motor sits at the top of the cavity and distributes microwaves evenly. If the stirrer motor is stuck, microwaves concentrate in one area, causing uneven cooking. Our technician tests the stirrer motor and replaces it if faulty.",
      "In some cases, uneven heating is caused by a faulty waveguide — the metal channel that guides microwaves from the magnetron to the cavity. Our technician inspects the waveguide for damage or misalignment.",

      "How Our Microwave Repair Process Works",
      "Understanding our repair process helps you know what to expect when you book a microwave repair in Bengaluru.",
      "Step 1: Tell us the symptom. Use our diagnostic quiz or call us. Share the brand, type (solo, grill, convection), and the symptom (not heating, sparking, etc.).",
      "Step 2: Free diagnosis. Our technician visits your home, inspects the microwave, and identifies the exact fault. We use multimeters and component testers to pinpoint the problem — no guesswork.",
      "Step 3: Transparent quote. After diagnosis, we share a clear quote for the repair. You approve before any work begins. No surprises.",
      "Step 4: Repair at home. Most microwave repairs are completed in 30-60 minutes at your doorstep. We use genuine spare parts from the original manufacturer. If a specific part needs to be procured, we return within 24 hours.",
      "Step 5: Quality assured. All repairs are quality assured. If the same issue recurs, we fix it free.",

      "Brands We Service in Bengaluru",
      "We repair microwave ovens from all major brands sold in Bengaluru:",
      "Samsung microwave repair in Bengaluru — solo, grill, and convection models. We carry genuine Samsung magnetrons, fuses, door switches, turntable motors, and control panels.",
      "LG microwave repair in Bengaluru — solo, grill, convection, and lightwave models. We carry genuine LG spare parts.",
      "IFB microwave repair in Bengaluru — all IFB convection and grill models.",
      "Whirlpool microwave repair in Bengaluru — all Whirlpool models.",
      "Bajaj microwave repair in Bengaluru — all Bajaj models.",
      "Godrej microwave repair in Bengaluru — all Godrej models.",
      "Panasonic microwave repair in Bengaluru — all Panasonic models including inverter microwaves.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, microwave oven repair is one of our most requested services. The city's fast-paced lifestyle, with many residents working in IT hubs like Whitefield, Electronic City, and Koramangala, means the microwave is used daily — for reheating, defrosting, and quick meals. Heavy use leads to faster wear of components like the magnetron, waveguide cover, and turntable motor.",
      "From Indiranagar and Koramangala to Whitefield and Marathahalli, residents rely on same-day microwave repair. Whether you're in Jayanagar looking for Samsung microwave repair near Jayanagar 4th Block, or in Hebbal searching for LG microwave repair in Hebbal, our verified technicians reach every corner of Bengaluru within 45 to 60 minutes. Same-day slots are available across all 84+ neighbourhoods.",
      "Bengaluru's power supply can be unstable in certain areas, which stresses microwave internal components. Areas like Marathahalli, HSR Layout, and BTM Layout experience more voltage fluctuations, leading to more fuse and control board failures. If you live in these areas, we recommend using a voltage stabiliser to protect your microwave.",

      "Microwave repair near me in Bengaluru",
      "Looking for microwave repair near you? We serve all of Bengaluru. Here are some areas where we provide same-day microwave repair:",
      "Microwave repair in Indiranagar. Microwave repair in Koramangala. Microwave repair in Whitefield. Microwave repair in HSR Layout. Microwave repair in Jayanagar. Microwave repair in Marathahalli. Microwave repair in BTM Layout. Microwave repair in Electronic City. Microwave repair in Hebbal. Microwave repair in Malleswaram. Microwave repair in Rajajinagar. Microwave repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — Microwave Repair in Bengaluru",
      "When you search for microwave repair in Bengaluru, three names will come up — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your microwave.",
      "Urban Company is a well-known national platform offering multiple home services. Their app is polished and booking is straightforward. However, their technicians are often generalists handling many appliance categories — which means they may not carry microwave-specific spare parts like magnetrons, waveguide covers, or membrane switches on the first visit. You might face a revisit for parts. Their pricing structure includes a platform visit fee, and same-day slots in Bengaluru are not always guaranteed during peak hours.",
      "Local Ramu is a Bengaluru-based repair provider covering several appliance types. Being local, they understand the city well. However, their technician pool is smaller, which can mean longer wait times during peak hours. They also don't always carry brand-specific microwave parts for all seven major brands we service — Samsung, LG, IFB, Whirlpool, Bajaj, Godrej, and Panasonic. If your microwave needs a specific magnetron or control panel, they may need to source it, adding delay.",
      "Urban Service Company is Bengaluru-born, microwave-specialist, and carries genuine spare parts for all major brands on every visit. Our technicians are trained specifically on microwave diagnostics — magnetron resistance testing, waveguide cover inspection, turntable motor replacement, membrane switch and control board diagnosis, door switch testing, and thermal fuse replacement. Same-day slots are available across all 84+ neighbourhoods. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want a microwave specialist with genuine parts, same-day service, and no platform fee across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — Microwave repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for microwave repair? Urban Service Company is Bengaluru-focused and microwave-specialist, carrying genuine brand-specific parts on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts. We offer same-day slots, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for microwave repair? Both are local to Bengaluru. Urban Service Company specialises in microwave repair with trained technicians and genuine parts for all seven major brands. Local Ramu is a generalist with a smaller technician pool. For microwave-specific faults like magnetron failure or waveguide cover damage, a specialist is recommended.",
      "Do you repair all microwave brands in Bengaluru? Yes. We repair Samsung, LG, IFB, Whirlpool, Bajaj, Godrej, and Panasonic microwave ovens — solo, grill, and convection models.",
      "How fast can a technician reach my home? Same-day slots are available across Bengaluru. Once you share your appliance and symptom, our technician typically reaches your home within 45 to 60 minutes in most neighbourhoods.",
      "Is diagnosis free? Yes. Diagnosis is free when you proceed with the repair. We share the quote before any work begins.",
      "Do you carry spare parts? Yes. Our technicians carry common spare parts — magnetrons, fuses, door switches, waveguide covers, turntable motors, and control panels. If a specific part needs to be procured, we return within 24 hours.",
      "Is the repair quality assured? Yes. All microwave repairs done by Urban Service Company are quality assured. If the same issue recurs, we fix it free.",
      "Can you fix a sparking microwave? Yes. Sparking is usually caused by a damaged waveguide cover. Our technician replaces the cover and inspects the magnetron for damage.",
      "Is it safe to use a microwave that's sparking? No. Stop using it immediately. Sparking can damage the magnetron and, in rare cases, cause a fire. Call us for same-day repair.",

      "Final takeaway",
      "Microwave oven repair in Bengaluru doesn't have to be a hassle. Understanding the common faults — magnetron failure, waveguide cover damage, turntable motor wear, membrane switch failure, fuse and door switch issues — helps you describe the problem accurately when you call.",
      "With the right technician, genuine spare parts, and a quality assured repair, your microwave can be back to full working order in 30-60 minutes. Don't attempt DIY repairs — microwaves contain high-voltage components that can be dangerous even when unplugged.",
      "Call us for same-day microwave repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
  {
    slug: "ac-repair-bengaluru-complete-guide",
    title: "AC Repair in Bengaluru — Complete Diagnostic Guide 2026",
    excerpt:
      "AC not cooling, gas refill, water leakage, noise, PCB failure? This complete guide explains every common AC fault, its cause, and how our technicians diagnose and fix it — for Daikin, LG, Samsung, Voltas, Hitachi, Panasonic across 84+ Bengaluru neighbourhoods.",
    category: "AC Repair",
    date: "2026-07-10",
    readTime: "14 min read",
    image: "/blog/ac-problems.png",
    content: [
      "Bengaluru's summer pushes your AC to its limits. When it stops cooling, leaks water, or makes noise, you need fast, reliable repair. This guide breaks down every common AC fault, what causes it, and how our technicians diagnose and fix it.",
      "AC repair in Bengaluru is in high demand from March to June, with peak requests from areas like Whitefield, Electronic City, and Koramangala where IT professionals work from home and need a cool environment. This content is intended for Bengaluru residents who want to understand what's wrong with their AC before calling a technician.",
      "This guide covers faults for all major AC brands — Daikin, LG, Samsung, Voltas, Hitachi, Panasonic, Blue Star, Carrier, O-General and more. Whether you have a split AC or window AC, inverter or non-inverter, the diagnostic process is similar. The difference lies in the spare parts and internal architecture.",
      "If your AC is under warranty, contact the brand's authorised service centre first. If the warranty has expired or you need same-day repair, Urban Service Company provides free diagnosis, genuine spare parts, and quality assured repairs across Bengaluru.",

      "Why AC Faults Happen",
      "ACs fail for several reasons — lack of regular servicing, dirty filters and coils, gas leaks, electrical faults, and component wear. Understanding the root cause helps prevent recurring issues.",
      "The most common causes of AC failure in Bengaluru are lack of servicing (filters and coils clog with dust, reducing cooling and straining the compressor), voltage fluctuations (damaging capacitors and PCBs), gas leaks (from vibration, corrosion, or poor installation), and natural wear of components like fan motors and compressors over time.",
      "Bengaluru's environment plays a role too. The city's dust levels, especially in areas under construction like Whitefield and Sarjapur Road, clog AC filters faster than in other cities. During the monsoon (June-September), humidity causes mould and bacteria buildup in the indoor unit coil, leading to bad smell and reduced cooling.",

      "1. AC Not Cooling — Low Gas, Faulty Capacitor, or Dirty Coil",
      "An AC that's running but not cooling is the most common complaint in Bengaluru. The cause could be low refrigerant gas, a faulty capacitor, a dirty evaporator coil, a blocked condenser coil, or a defective compressor.",
      "Low refrigerant gas is the #1 cause of poor cooling. Refrigerant leaks from joints, valves, or corroded copper tubes. When gas levels drop, the AC can't absorb heat from your room. Our technician tests gas pressure, identifies leaks using nitrogen and soap solution, fixes the leaks by brazing, and refills gas by weight.",
      "A faulty capacitor prevents the compressor from starting. The capacitor stores the energy needed to kick-start the compressor motor. When it fails, you hear a clicking sound but the compressor doesn't start. Capacitor failure is common in Bengaluru due to voltage fluctuations. Our technician tests the capacitor with a multimeter and replaces it with a genuine spare.",
      "A dirty evaporator coil (indoor unit) blocks airflow and reduces heat absorption. Dust and debris accumulate on the coil fins, insulating them from the room air. Our technician cleans the coil with a foam jet and power jet, restoring full cooling performance.",
      "A blocked condenser coil (outdoor unit) prevents heat rejection. The outdoor unit releases heat absorbed from your room. If the condenser coil is clogged with dust, leaves, or debris, heat can't escape. Our technician cleans the outdoor coil and ensures proper airflow around the unit.",
      "A defective compressor is the most serious AC fault. The compressor is the heart of the AC — it pumps refrigerant through the system. Compressor failure can be caused by low gas (compressor overheats without enough refrigerant), voltage fluctuations, or age. Our technician tests the compressor's electrical readings and recommends repair or replacement.",

      "2. AC Gas Refill — Leak Detection and Refilling Process",
      "AC gas refill is one of the most searched AC repair services in Bengaluru. If your AC is not cooling and you suspect low gas, here's what the process involves.",
      "First, our technician checks the gas pressure using a manifold gauge. Low pressure indicates a leak somewhere in the system. Simply refilling gas without fixing the leak means the gas will leak out again — sometimes within weeks.",
      "Leak detection: Our technician pressurises the system with nitrogen and applies soap solution to all joints, valves, and copper tube connections. Bubbles form at the leak point. For harder-to-find leaks, we use electronic leak detectors. Once the leak is found, we fix it by brazing (welding) the joint or replacing the damaged tube.",
      "Vacuum: After fixing the leak, we vacuum the system to remove air and moisture. Air in the system reduces cooling efficiency and can damage the compressor. Moisture in the system freezes at the expansion valve, blocking refrigerant flow.",
      "Gas refill: We refill the refrigerant by weight, not by pressure. Each AC has a specific gas quantity listed on the nameplate. Overfilling or underfilling reduces efficiency and can damage the compressor. We use a digital scale for accuracy.",
      "Post-refill check: After refilling, our technician checks the AC's cooling performance — temperature differential between room air and supply air, compressor amperage, and system pressure. This confirms the repair is complete and the AC is cooling optimally.",

      "3. Water Leakage from Indoor Unit — Clogged Drain Pipe",
      "Water dripping from the indoor unit is a common AC problem in Bengaluru, especially during the monsoon. The cause is almost always a clogged drain pipe.",
      "The indoor unit produces condensation as it cools the warm room air. This water flows through a drain tray and out through a drain pipe to the exterior. Over time, dust, algae, and debris block the drain pipe. Water backs up and overflows from the indoor unit.",
      "Our technician clears the drain pipe using a high-pressure pump or a flexible rod. We also clean the drain tray to remove any buildup. If the drain pipe is damaged or cracked, we replace it.",
      "In some cases, water leakage is caused by a damaged drain tray (the plastic tray under the evaporator coil). If the tray is cracked, water leaks directly from the indoor unit. Our technician inspects the tray and replaces it if needed.",
      "Another cause is a frozen evaporator coil. When the coil freezes (due to low gas or dirty filter), ice builds up. When the ice melts, water overflows the drain tray. Fixing the root cause (gas refill or filter cleaning) stops the freezing and the leakage.",
      "Prevention: During annual AC servicing, our technician checks and clears the drain pipe. We recommend servicing your AC twice a year — before summer and during the monsoon.",

      "4. AC Not Turning On — Capacitor, PCB, or Power Supply",
      "An AC that won't turn on has an electrical fault. The most common causes are a faulty capacitor, a tripped PCB, a blown fuse, or a power supply issue.",
      "Capacitor failure: The capacitor provides the initial energy boost to start the compressor motor. When it fails, the AC makes a humming sound but the compressor doesn't start. Capacitor failure is very common in Bengaluru due to voltage fluctuations, especially in areas like Marathahalli, HSR Layout, and BTM Layout. Our technician tests the capacitor and replaces it with a genuine spare.",
      "PCB (Printed Circuit Board) failure: The PCB controls all AC functions — compressor, fan motor, swing motor, display, and sensors. A tripped or damaged PCB prevents the AC from turning on. Non-inverter ACs have simpler PCBs; inverter ACs have more complex boards with variable frequency drives. Our technicians are trained to diagnose and repair both types.",
      "Power supply issues: A tripped circuit breaker or a blown fuse cuts power to the AC. Our technician checks the electrical supply, circuit breaker, and wiring. If the AC is on a shared circuit with other high-power appliances, we recommend a dedicated circuit.",
      "Faulty thermostat or sensor: The room temperature sensor tells the PCB when to start and stop cooling. A faulty sensor causes the AC to not turn on or to run continuously. Our technician tests the sensor and replaces it if needed.",

      "5. AC Noise or Vibration — Fan Motor, Blower, or Bearing",
      "A noisy AC is annoying and often indicates a mechanical problem. The noise can come from the indoor unit or the outdoor unit.",
      "Indoor unit noise: A faulty indoor fan motor makes a whirring, grinding, or squeaking sound. The noise increases with fan speed. Common causes are worn bearings, a loose blower wheel, or a damaged fan blade. Our technician inspects the fan motor, blower, and blade, and replaces the faulty part.",
      "Outdoor unit noise: The outdoor unit contains the compressor, condenser fan, and condenser coil. Compressor noise — a loud humming or grinding — indicates internal compressor wear. Condenser fan noise — a rattling or clicking — indicates a loose or damaged fan blade. Our technician identifies the noise source and recommends the right fix.",
      "Vibration: Excess vibration is caused by an unlevelled outdoor unit, loose mounting bolts, or worn rubber dampers. Our technician levels the unit, tightens bolts, and replaces worn dampers.",
      "Refrigerant line noise: A hissing or bubbling sound from the refrigerant lines can indicate a gas leak or restricted flow. Our technician checks the lines for leaks and proper insulation.",

      "6. AC Installation and Uninstallation",
      "Proper AC installation is critical for performance and longevity. A poorly installed AC causes cooling issues, water leakage, noise, and premature component failure.",
      "Our installation process: We mount the indoor unit on a wall bracket, ensuring it's level and securely fastened. We mount the outdoor unit on a concrete base or wall bracket, ensuring proper clearance for airflow. We connect the refrigerant lines with proper insulation, flare the connections, and check for leaks. We connect the electrical wiring through a dedicated circuit. We vacuum the system to remove air and moisture. We test the AC's cooling performance after installation.",
      "AC uninstallation: We safely disconnect the refrigerant lines, recover the gas (don't release it into the atmosphere), disconnect the electrical wiring, remove both units, and patch the wall holes.",
      "We install and uninstall both split and window ACs for all brands — Daikin, LG, Samsung, Voltas, Hitachi, Panasonic, Blue Star, Carrier, O-General and more.",

      "7. AC Servicing — Foam Jet and Power Jet Cleaning",
      "Regular AC servicing is the single most important thing you can do to prevent AC faults. Servicing cleans the filters, coils, fins, and drain tray — restoring cooling performance and reducing electricity bills.",
      "Foam jet service: Our technician sprays a specialised foam cleaner on the evaporator coil, filters, and fins. The foam dissolves dust, oil, and biological growth. After 10-15 minutes, we rinse with a power jet (high-pressure water spray). This deep-cleans the indoor unit.",
      "Power jet service: For heavily soiled ACs, we use a high-pressure power jet to blast away stubborn dirt from the coil fins. We also clean the drain tray and drain pipe to prevent water leakage.",
      "Anti-rust deep clean: We apply an anti-rust treatment to the coil fins to prevent corrosion. This is especially important in humid areas like Bengaluru during the monsoon.",
      "We recommend servicing your AC twice a year — once before summer (March-April) and once during the monsoon (July-August).",

      "How Our AC Repair Process Works",
      "Understanding our repair process helps you know what to expect when you book an AC repair in Bengaluru.",
      "Step 1: Tell us the symptom. Share the brand, type (split or window, inverter or non-inverter), and the symptom (not cooling, water leakage, noise, etc.).",
      "Step 2: Free diagnosis. Our technician visits your home, inspects the indoor and outdoor units, and identifies the exact fault using manifold gauges, multimeters, and leak detectors.",
      "Step 3: Transparent quote. After diagnosis, we share a clear quote. You approve before any work begins.",
      "Step 4: Repair at home. Most AC repairs are completed in 45-90 minutes at your doorstep. We use genuine spare parts. Gas refill and compressor work may take longer.",
      "Step 5: Quality assured. All AC repairs are quality assured.",

      "Brands We Service in Bengaluru",
      "We repair ACs from all major brands sold in Bengaluru:",
      "Daikin AC repair in Bengaluru — split and inverter ACs. We carry genuine Daikin spare parts including capacitors, PCBs, fan motors, sensors, and remote controls.",
      "LG AC repair in Bengaluru — split, window, and inverter ACs. We carry genuine LG spare parts.",
      "Samsung AC repair in Bengaluru — split and inverter ACs.",
      "Voltas AC repair in Bengaluru — split and window ACs.",
      "Hitachi AC repair in Bengaluru — split and inverter ACs.",
      "Panasonic AC repair in Bengaluru — split and inverter ACs.",
      "Blue Star AC repair in Bengaluru — split and cassette ACs.",
      "Carrier AC repair in Bengaluru — split and window ACs.",
      "O-General AC repair in Bengaluru — split and window ACs.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, AC repair is one of our most requested services from March to June. The city's IT workforce, concentrated in areas like Whitefield, Electronic City, Koramangala, and Indiranagar, relies heavily on ACs for home comfort after long work hours.",
      "Bengaluru's unique challenge is the mix of old and new buildings. Older apartments in areas like Jayanagar and Malleswaram have outdated electrical wiring that causes voltage fluctuations, leading to more capacitor and PCB failures. Newer apartments in Whitefield and HSR Layout have better wiring but face dust from nearby construction, clogging AC filters faster.",
      "From Indiranagar to Whitefield, Jayanagar to Hebbal, our verified technicians reach every corner of Bengaluru within 45 to 60 minutes. Whether you're in Koramangala looking for Daikin AC repair near Koramangala, or in Marathahalli searching for AC gas refill in Marathahalli, same-day slots are available across all 84+ neighbourhoods.",

      "AC repair near me in Bengaluru",
      "Looking for AC repair near you? We serve all of Bengaluru. Here are some areas where we provide same-day AC repair:",
      "AC repair in Indiranagar. AC repair in Koramangala. AC repair in Whitefield. AC repair in HSR Layout. AC repair in Jayanagar. AC repair in Marathahalli. AC repair in BTM Layout. AC repair in Electronic City. AC repair in Hebbal. AC repair in Malleswaram. AC repair in Rajajinagar. AC repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — AC Repair in Bengaluru",
      "When you search for AC repair in Bengaluru, you'll come across three names — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your air conditioner.",
      "Urban Company is a national home services platform with a well-designed app and broad service catalogue. Their AC repair service covers multiple brands. However, their technicians are generalists handling many appliance types — which means they may not carry AC-specific spare parts like capacitors, PCBs, fan motors, or refrigerant gas on the first visit. AC gas refill requires a manifold gauge, vacuum pump, and digital scale — not all generalist technicians carry this equipment. Their pricing includes a platform visit fee, and same-day slots during Bengaluru's peak summer (March-June) are often fully booked.",
      "Local Ramu is a Bengaluru-based repair provider. Being local, they know the city's areas and AC usage patterns. However, their technician pool is smaller — during peak summer when AC failures spike across Whitefield, Electronic City, and Koramangala, wait times can stretch. They also may not carry genuine brand-specific spare parts for all nine AC brands we service — Daikin, LG, Samsung, Voltas, Hitachi, Panasonic, Blue Star, Carrier, and O-General. Inverter AC PCB repair requires specialised diagnostic equipment that generalist technicians may not have.",
      "Urban Service Company is Bengaluru-born, AC-specialist, and carries genuine spare parts and full gas refill equipment on every visit. Our technicians are trained specifically on AC diagnostics — manifold gauge pressure testing, nitrogen leak detection, vacuum pump evacuation, gas refill by weight, capacitor testing, PCB diagnosis, fan motor inspection, and coil cleaning with foam jet and power jet. Same-day slots are available across all 84+ neighbourhoods — even during peak summer. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want an AC specialist with genuine parts, full gas refill equipment, and same-day service across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — AC repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for AC repair? Urban Service Company is AC-specialist with genuine brand-specific parts and full gas refill equipment on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts or gas. We offer same-day slots even during peak summer, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for AC repair? Both are Bengaluru-local. Urban Service Company specialises in AC repair with trained technicians, genuine parts for all nine major brands, and full gas refill equipment. Local Ramu is a generalist with a smaller technician pool. For AC-specific faults like gas leaks, PCB failure, or compressor issues, a specialist is recommended.",
      "Do you repair both split and window ACs? Yes. We repair all types of split and window ACs in Bengaluru — inverter and non-inverter.",
      "How fast can a technician reach my home? Same-day slots are available. Our technician typically reaches your home within 45 to 60 minutes in most neighbourhoods.",
      "Is diagnosis free? Yes. Diagnosis is free when you proceed with the repair. We share the quote before any work begins.",
      "Do you carry genuine spare parts? Yes. Our technicians carry common spare parts — capacitors, fan motors, sensors, remote controls, and filters. Gas refill equipment is also carried. If a specific part needs to be procured, we return within 24 hours.",
      "Is the repair quality assured? Yes. All AC repairs are quality assured. If the same issue recurs, we fix it free.",
      "How often should I service my AC? We recommend servicing your AC twice a year — once before summer and once during the monsoon. Clean the filter every 2 weeks during summer.",
      "Can you fix a leaking AC? Yes. Water leakage is usually caused by a clogged drain pipe. Our technician clears the blockage and checks the drain tray and pipe.",

      "Final takeaway",
      "AC repair in Bengaluru doesn't have to be a frustrating experience. Understanding the common faults — low gas, capacitor failure, water leakage, PCB issues, fan motor noise, and dirty coils — helps you describe the problem accurately when you call.",
      "With the right technician, genuine spare parts, and a quality assured repair, your AC can be back to full cooling in 45-90 minutes. Regular servicing — twice a year — prevents most faults before they happen.",
      "Call us for same-day AC repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
  {
    slug: "washing-machine-repair-bengaluru-complete-guide",
    title: "Washing Machine Repair in Bengaluru — Complete Diagnostic Guide 2026",
    excerpt:
      "Washing machine not draining, not spinning, noisy drum, door jammed? This complete guide explains every common washing machine fault for Samsung, LG, IFB, Bosch, Whirlpool across 84+ Bengaluru neighbourhoods.",
    category: "Washing Machine",
    date: "2026-07-05",
    readTime: "12 min read",
    image: "/blog/washing-machine-repair-vs-replace.png",
    content: [
      "Your washing machine handles one of the most important daily chores. When it stops working, laundry piles up and your routine is disrupted. This guide breaks down every common washing machine fault, what causes it, and how our technicians diagnose and fix it.",
      "Washing machine repair in Bengaluru covers front-load, top-load, and semi-automatic machines from all major brands — Samsung, LG, IFB, Bosch, Whirlpool, Godrej and Haier. This content is intended for Bengaluru residents who want to understand what's wrong with their washing machine before calling a technician.",
      "If your washing machine is under warranty, contact the brand's service centre first. If the warranty has expired or you need same-day repair, Urban Service Company provides free diagnosis, genuine spare parts, and quality assured repairs.",

      "Why Washing Machine Faults Happen",
      "Washing machines fail for several reasons — overloading, foreign objects in the drum, detergent residue buildup, electrical faults, and natural component wear. Understanding the root cause helps prevent recurring issues.",
      "The most common causes in Bengaluru are overloading (residents often wash large loads to save time), coins and keys left in pockets (damaging the drum and drain pump), hard water causing scale buildup in the drum and valves, and voltage fluctuations damaging the control board.",
      "Bengaluru's water quality varies by area — hard borewell water in Whitefield and Marathahalli causes faster scale buildup in the drum and inlet valve, while softer Cauvery water in Indiranagar and Jayanagar is gentler on the machine.",

      "1. Washing Machine Not Draining — Clogged Drain Pump",
      "Water staying in the drum after a wash cycle is the most common washing machine fault in Bengaluru. The cause is usually a clogged drain pump, a blocked drain hose, or a faulty drain motor.",
      "The drain pump pushes water out of the drum through the drain hose. Over time, lint, coins, buttons, and debris accumulate in the pump filter, blocking water flow. In some cases, the drain motor itself burns out.",
      "Our technician inspects the drain pump filter, removes any debris, checks the drain hose for kinks or blockages, and tests the drain motor with a multimeter. If the motor is faulty, we replace it with a genuine spare.",
      "Prevention: Check pockets before loading. Clean the drain pump filter monthly (usually located behind a small door at the bottom of the machine). Don't overload the machine.",

      "2. Washing Machine Not Spinning — Drive Belt, Motor, or Lid Switch",
      "If the drum doesn't spin during the wash or spin cycle, the cause could be a worn drive belt, a faulty motor, a broken lid switch, or a defective control board.",
      "The drive belt connects the motor to the drum. Over time, the belt stretches, cracks, or snaps. A worn belt causes the drum to spin slowly or not at all. Our technician inspects the belt and replaces it if worn.",
      "The motor drives the drum. In front-load machines, the motor is typically a universal motor or an inverter motor. A burnt motor causes the drum to not spin. Our technician tests the motor's electrical readings and replaces it if faulty.",
      "The lid switch (top-load machines) or door lock (front-load machines) is a safety device that prevents the machine from spinning when the door is open. A faulty switch prevents the spin cycle. Our technician tests the switch and replaces it.",
      "The control board manages all washing machine functions. If the board doesn't send the spin signal, the drum won't spin. Our technician tests the board and repairs or replaces it.",

      "3. Noisy Drum — Worn Bearing or Foreign Object",
      "A grinding, rumbling, or rattling sound during the spin cycle indicates a mechanical problem. The most common causes are a worn drum bearing, a loose drum, or a foreign object trapped inside.",
      "The drum bearing allows the drum to rotate smoothly. Over years of use, the bearing wears out, causing a loud grinding noise during spin. Bearing replacement is a complex repair — the entire drum assembly needs to be dismantled. Our technician replaces the bearing with a genuine spare.",
      "A loose drum indicates worn shock absorbers (front-load) or worn suspension springs (top-load). The drum moves excessively during spin, causing banging sounds. Our technician inspects and replaces the worn components.",
      "Foreign objects — coins, keys, buttons, bra wires — trapped between the inner and outer drum cause rattling and scraping sounds. Our technician removes the foreign object and checks for any drum damage.",

      "4. Door Jammed — Faulty Door Lock",
      "A jammed door is common in front-load washing machines. The door won't open after a wash cycle, trapping your clothes inside.",
      "The door lock is a safety device that keeps the door closed during operation. A faulty lock, a trapped garment in the seal, or a drained pump that won't release the lock can prevent the door from opening.",
      "Our technician safely opens the door, checks for trapped objects, inspects the door lock, and replaces it if faulty. If the lock mechanism is jammed due to water pressure (the machine thinks there's still water inside), we clear the drain system first.",
      "Prevention: Don't overload the machine. Check the door seal for trapped items after every wash. Don't force the door open.",

      "5. Washing Machine Not Starting — Control Board or Door Lock",
      "A washing machine that won't start at all — no lights, no display, no response — has an electrical fault. The most common causes are a faulty power supply, a defective control board, or a broken door lock.",
      "Power supply: Our technician checks the power outlet, power cord, and internal wiring. A tripped circuit breaker or a blown internal fuse can prevent the machine from starting.",
      "Control board: The control board is the brain of the washing machine. If it's faulty, the machine won't respond. Our technician tests the board and repairs or replaces it.",
      "Door lock: If the machine doesn't detect the door as closed, it won't start. Our technician tests the door lock and replaces it if faulty.",

      "6. Water Inlet Issues — Clogged Filter or Faulty Valve",
      "If water is not entering the machine, the inlet filter or inlet valve is likely faulty.",
      "The inlet filter sits at the connection between the water hose and the machine. It catches sediment and debris from the water supply. In Bengaluru, hard borewell water clogs the filter faster. Our technician cleans or replaces the filter.",
      "The inlet valve opens to let water in. If the valve is faulty, water doesn't enter the machine. Our technician tests the valve with a multimeter and replaces it with a genuine spare.",

      "7. Foul Smell — Mould and Detergent Buildup",
      "A washing machine that smells bad is caused by mould, bacteria, and detergent residue buildup in the drum, door seal, and drain filter.",
      "Bengaluru's humid climate, especially during the monsoon (June-September), accelerates mould growth. Front-load machines are more prone to this because the rubber door seal traps moisture.",
      "Our technician deep-cleans the drum, door seal, and drain filter. We also recommend leaving the door open after every wash to let the drum dry, and running a monthly maintenance wash at 60°C with a descaler.",

      "8. Excess Vibration — Unlevelled Machine or Worn Shock Absorbers",
      "A washing machine that walks across the floor or shakes violently during spin has a mechanical or installation issue.",
      "An unlevelled machine causes the drum to be off-centre, leading to vibration. Our technician levels the machine using the adjustable feet.",
      "Worn shock absorbers (front-load) or worn suspension springs (top-load) cause excessive drum movement. Our technician inspects and replaces these components.",
      "An overloaded machine also causes excess vibration. Always follow the manufacturer's load capacity guidelines.",

      "How Our Washing Machine Repair Process Works",
      "Step 1: Tell us the symptom. Share the brand, type (front-load, top-load, semi-automatic), and the symptom.",
      "Step 2: Free diagnosis. Our technician visits your home, inspects the machine, and identifies the exact fault.",
      "Step 3: Transparent quote. After diagnosis, we share a clear quote. You approve before any work begins.",
      "Step 4: Repair at home. Most repairs are completed in 45-90 minutes. We use genuine spare parts.",
      "Step 5: Quality assured. All repairs are quality assured.",

      "Brands We Service in Bengaluru",
      "Samsung washing machine repair in Bengaluru — front-load, top-load, and semi-automatic. We carry genuine Samsung spare parts.",
      "LG washing machine repair in Bengaluru — front-load and top-load. We carry genuine LG spare parts.",
      "IFB washing machine repair in Bengaluru — front-load and top-load.",
      "Bosch washing machine repair in Bengaluru — front-load.",
      "Whirlpool washing machine repair in Bengaluru — top-load and semi-automatic.",
      "Godrej washing machine repair in Bengaluru — top-load and semi-automatic.",
      "Haier washing machine repair in Bengaluru — top-load and semi-automatic.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, washing machine repair is one of our top three services. The city's busy IT workforce, concentrated in areas like Whitefield, Electronic City, and Koramangala, relies on washing machines to handle daily laundry efficiently.",
      "Bengaluru's water quality challenges — hard borewell water in some areas — causes faster scale buildup in washing machine drums and inlet valves. Areas like Marathahalli, HSR Layout, and BTM Layout experience more inlet valve clogs due to sediment in the water supply.",
      "From Indiranagar to Whitefield, Jayanagar to Hebbal, our verified technicians reach every corner of Bengaluru within 45 to 60 minutes. Same-day slots are available across all 84+ neighbourhoods.",

      "Washing machine repair near me in Bengaluru",
      "Looking for washing machine repair near you? We serve all of Bengaluru:",
      "Washing machine repair in Indiranagar. Washing machine repair in Koramangala. Washing machine repair in Whitefield. Washing machine repair in HSR Layout. Washing machine repair in Jayanagar. Washing machine repair in Marathahalli. Washing machine repair in BTM Layout. Washing machine repair in Electronic City. Washing machine repair in Hebbal. Washing machine repair in Malleswaram. Washing machine repair in Rajajinagar. Washing machine repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — Washing Machine Repair in Bengaluru",
      "When you search for washing machine repair in Bengaluru, three names will appear — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your washing machine.",
      "Urban Company is a national home services platform with a clean app experience. Their washing machine repair covers multiple brands. However, their technicians are generalists handling many appliance types — which means they may not carry washing machine-specific spare parts like drain pumps, drive belts, door locks, drum bearings, or inlet valves on the first visit. Drum bearing replacement is a complex repair requiring full drum dismantling — not all generalist technicians have the experience or tools for this. Their pricing includes a platform visit fee, and same-day slots during weekends (when most Bengaluru residents do laundry) are often fully booked.",
      "Local Ramu is a Bengaluru-based repair provider. Being local, they understand the city's water quality challenges — hard borewell water in Whitefield and Marathahalli causes faster scale buildup in washing machines. However, their technician pool is smaller, which means longer wait times during peak hours. They also may not carry genuine brand-specific spare parts for all seven brands we service — Samsung, LG, IFB, Bosch, Whirlpool, Godrej, and Haier. Front-load door lock replacement and control board diagnosis require specialised knowledge that generalist technicians may not have.",
      "Urban Service Company is Bengaluru-born, washing machine-specialist, and carries genuine spare parts on every visit. Our technicians are trained specifically on washing machine diagnostics — drain pump inspection, drive belt replacement, drum bearing replacement (full dismantling), door lock repair, control board testing, inlet valve cleaning, and deep drum cleaning for mould and odour. Same-day slots are available across all 84+ neighbourhoods. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want a washing machine specialist with genuine parts, drum bearing expertise, and same-day service across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — Washing machine repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for washing machine repair? Urban Service Company is washing machine-specialist with genuine brand-specific parts on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts. We offer same-day slots, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for washing machine repair? Both are Bengaluru-local. Urban Service Company specialises in washing machine repair with trained technicians and genuine parts for all seven major brands. Local Ramu is a generalist with a smaller technician pool. For washing machine-specific faults like drum bearing wear or control board failure, a specialist is recommended.",
      "Do you repair all washing machine brands? Yes. We repair Samsung, LG, IFB, Bosch, Whirlpool, Godrej, and Haier — front-load, top-load, and semi-automatic.",
      "How fast can a technician reach my home? Same-day slots. Our technician typically reaches within 45 to 60 minutes.",
      "Is diagnosis free? Yes. Diagnosis is free when you proceed with the repair.",
      "Do you carry genuine spare parts? Yes. Our technicians carry common parts — drain pumps, belts, door locks, bearings, inlet valves, and control boards.",
      "Is the repair quality assured? Yes. All washing machine repairs are quality assured.",
      "My front-load door is jammed — can you open it? Yes. Our technician safely opens the door and replaces the lock if needed.",
      "Why does my washing machine smell? Mould and detergent buildup. Our technician deep-cleans the drum, seal, and filter.",

      "Final takeaway",
      "Washing machine repair in Bengaluru doesn't have to be stressful. Understanding common faults — not draining, not spinning, noisy drum, door jammed, not starting, inlet issues, foul smell, excess vibration — helps you describe the problem accurately.",
      "With the right technician, genuine spare parts, and a quality assured repair, your washing machine can be back to full working order in 45-90 minutes. Regular maintenance — cleaning the filter, leaving the door open, and monthly descaling — prevents most faults.",
      "Call us for same-day washing machine repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
  {
    slug: "refrigerator-repair-bengaluru-complete-guide",
    title: "Refrigerator Repair in Bengaluru — Complete Diagnostic Guide 2026",
    excerpt:
      "Refrigerator not cooling, frost buildup, water leakage, compressor noise, door seal? This complete guide explains every common fridge fault for Samsung, LG, Whirlpool, Godrej, Haier across 84+ Bengaluru neighbourhoods.",
    category: "Refrigerator",
    date: "2026-06-28",
    readTime: "12 min read",
    image: "/blog/refrigerator-signs.png",
    content: [
      "Your refrigerator runs 24/7, keeping your food fresh and safe. When it stops cooling, food spoils within hours. This guide breaks down every common refrigerator fault, what causes it, and how our technicians diagnose and fix it.",
      "Refrigerator repair in Bengaluru covers all brands — Samsung, LG, Whirlpool, Godrej, Haier, Panasonic, Bosch and more. Single door, double door, side-by-side, and door-in-door models. This content is intended for Bengaluru residents who want to understand what's wrong with their fridge before calling a technician.",

      "Why Refrigerator Faults Happen",
      "Refrigerators fail due to dirty condenser coils, door seal damage, thermostat wear, gas leaks, compressor age, and electrical faults. Bengaluru's warm climate means the fridge works harder than in cooler cities, accelerating component wear.",
      "The most common causes are dirty condenser coils (reducing heat rejection, straining the compressor), damaged door seals (letting cold air escape, making the compressor run continuously), and voltage fluctuations (damaging the relay and compressor).",

      "1. Refrigerator Not Cooling — Compressor, Thermostat, or Gas",
      "A fridge that's running but not cooling can have a faulty compressor, a defective thermostat, a gas leak, a blocked condenser coil, or a failed fan motor.",
      "The compressor pumps refrigerant through the system. If it fails, the fridge stops cooling entirely. Compressor failure is often caused by low gas (the compressor overheats without enough refrigerant), voltage fluctuations, or age. Our technician tests the compressor's electrical readings and recommends repair or replacement.",
      "The thermostat controls the temperature by cycling the compressor on and off. A faulty thermostat causes the fridge to run continuously (over-freezing) or not run at all (not cooling). Our technician tests the thermostat and replaces it.",
      "Gas leaks reduce the refrigerant level, causing poor cooling. Gas leaks from corroded tubes, loose joints, or vibration damage. Our technician detects leaks, fixes them, and refills the gas.",
      "Dirty condenser coils (at the back or bottom of the fridge) can't release heat efficiently. The compressor works harder and cooling drops. Our technician cleans the coils.",
      "A failed fan motor (condenser fan or evaporator fan) reduces airflow, causing poor cooling and uneven temperatures. Our technician tests and replaces faulty fans.",

      "2. Frost Buildup — Defrost System Failure",
      "Frost buildup in the freezer compartment indicates a defrost system failure. The defrost system melts frost that naturally accumulates on the evaporator coil. When it fails, ice builds up and blocks airflow.",
      "The defrost system has three components: the defrost timer (controls when defrost happens), the defrost heater (melts the ice), and the defrost sensor/thermostat (triggers the heater). Our technician tests all three and replaces the faulty one.",
      "A blocked defrost drain also causes frost buildup. When the drain is clogged, water from defrosting can't flow out and freezes. Our technician clears the drain.",

      "3. Water Leakage — Clogged Defrost Drain",
      "Water pooling on the floor or inside the fridge is usually caused by a clogged defrost drain. During the defrost cycle, ice melts into water that flows through the drain to the drip pan at the back. When the drain is blocked, water overflows.",
      "Our technician clears the drain using a flexible rod or hot water. We also check the drip pan for cracks and the water inlet valve for leaks.",

      "4. Compressor Noise — Fan, Bearing, or Vibration",
      "A noisy fridge — humming, clicking, grinding, or rattling — indicates a mechanical problem. The noise can come from the compressor, condenser fan, evaporator fan, or vibration.",
      "Compressor noise: A loud humming or grinding from the compressor indicates internal wear. A clicking sound means the relay is trying to start the compressor but failing. Our technician tests the compressor and relay.",
      "Condenser fan noise: A rattling sound from the back of the fridge usually means a loose or damaged fan blade. Our technician inspects and replaces the fan.",
      "Evaporator fan noise: A squeaking sound from inside the freezer indicates a worn evaporator fan bearing. Our technician replaces the fan motor.",
      "Vibration: A vibrating fridge is caused by an unlevelled unit or loose components. Our technician levels the fridge and tightens any loose parts.",

      "5. Door Seal Damage — Cooling Loss",
      "A loose, torn, or hardened door gasket lets cold air escape. The compressor runs continuously to compensate, increasing electricity bills and causing uneven cooling and frost buildup.",
      "Our technician inspects the door seal, identifies damage, and fits a genuine replacement gasket. We also check the door alignment — a misaligned door can damage even a new seal.",

      "6. Over-Freezing — Thermostat or Sensor",
      "If the refrigerator compartment freezes food (liquids freeze, vegetables get frost), the thermostat or temperature sensor is faulty. The fridge runs continuously without cycling off.",
      "Our technician tests the thermostat and temperature sensor, and replaces the faulty component.",

      "7. Refrigerator Not Starting — Relay, Overload, or Control Board",
      "A fridge that won't start at all has an electrical fault. The most common causes are a faulty relay, a tripped overload protector, or a defective control board.",
      "The relay and overload protector work together to start the compressor. A faulty relay makes a clicking sound but the compressor doesn't start. Our technician tests and replaces the relay and overload.",
      "The control board manages all fridge functions. If it's faulty, the fridge won't start. Our technician tests the board and repairs or replaces it.",

      "How Our Refrigerator Repair Process Works",
      "Step 1: Tell us the symptom. Share the brand, type (single door, double door, side-by-side), and the symptom.",
      "Step 2: Free diagnosis. Our technician visits your home and identifies the fault.",
      "Step 3: Transparent quote. We share a clear quote. You approve before any work.",
      "Step 4: Repair at home. Most repairs take 45-90 minutes. Genuine spare parts.",
      "Step 5: Quality assured. All repairs are quality assured.",

      "Brands We Service in Bengaluru",
      "Samsung refrigerator repair in Bengaluru — single door, double door, side-by-side, door-in-door.",
      "LG refrigerator repair in Bengaluru — all models.",
      "Whirlpool refrigerator repair in Bengaluru — all models.",
      "Godrej refrigerator repair in Bengaluru — all models.",
      "Haier refrigerator repair in Bengaluru — all models.",
      "Panasonic refrigerator repair in Bengaluru — all models.",
      "Bosch refrigerator repair in Bengaluru — all models.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, refrigerator repair is essential year-round due to the city's warm climate. Refrigerators work harder here than in cooler cities, accelerating component wear.",
      "From Indiranagar to Whitefield, Jayanagar to Hebbal, our verified technicians reach every corner. Same-day slots are available across all 84+ neighbourhoods.",

      "Refrigerator repair near me in Bengaluru",
      "Looking for refrigerator repair near you? We serve all of Bengaluru:",
      "Refrigerator repair in Indiranagar. Refrigerator repair in Koramangala. Refrigerator repair in Whitefield. Refrigerator repair in HSR Layout. Refrigerator repair in Jayanagar. Refrigerator repair in Marathahalli. Refrigerator repair in BTM Layout. Refrigerator repair in Electronic City. Refrigerator repair in Hebbal. Refrigerator repair in Malleswaram. Refrigerator repair in Rajajinagar. Refrigerator repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — Refrigerator Repair in Bengaluru",
      "When you search for refrigerator repair in Bengaluru, you'll find three names — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your fridge.",
      "Urban Company is a national home services platform with a clean app experience. Their refrigerator repair covers multiple brands. However, their technicians are generalists handling many appliance types — which means they may not carry fridge-specific spare parts like compressors, thermostats, relays, overload protectors, door gaskets, or fan motors on the first visit. Compressor testing requires electrical reading equipment, and gas leak detection requires nitrogen pressurisation — not all generalist technicians carry this. Their pricing includes a platform visit fee, and same-day slots during weekends are often fully booked.",
      "Local Ramu is a Bengaluru-based repair provider. Being local, they understand the city's warm climate and how hard fridges work here. However, their technician pool is smaller, which means longer wait times during peak hours. They also may not carry genuine brand-specific spare parts for all seven brands we service — Samsung, LG, Whirlpool, Godrej, Haier, Panasonic, and Bosch. Defrost system diagnosis — timer, heater, and sensor testing — requires specialised knowledge that generalist technicians may not have.",
      "Urban Service Company is Bengaluru-born, refrigerator-specialist, and carries genuine spare parts on every visit. Our technicians are trained specifically on refrigerator diagnostics — compressor electrical testing, thermostat replacement, gas leak detection with nitrogen, defrost system diagnosis (timer, heater, sensor), door seal inspection and replacement, condenser coil cleaning, and control board testing. Same-day slots are available across all 84+ neighbourhoods. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want a refrigerator specialist with genuine parts, compressor expertise, and same-day service across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — Refrigerator repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for refrigerator repair? Urban Service Company is refrigerator-specialist with genuine brand-specific parts on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts. We offer same-day slots, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for refrigerator repair? Both are Bengaluru-local. Urban Service Company specialises in refrigerator repair with trained technicians and genuine parts for all seven major brands. Local Ramu is a generalist with a smaller technician pool. For fridge-specific faults like compressor failure or defrost system issues, a specialist is recommended.",
      "Do you repair all refrigerator brands? Yes. Samsung, LG, Whirlpool, Godrej, Haier, Panasonic, Bosch — all types.",
      "How fast can a technician reach my home? Same-day slots. Typically within 45 to 60 minutes.",
      "Is diagnosis free? Yes. Free when you proceed with the repair.",
      "Do you carry genuine spare parts? Yes. Compressors, thermostats, fan motors, sensors, door seals, relays, and control boards.",
      "Is the repair quality assured? Yes. All refrigerator repairs are quality assured.",
      "My fridge is not cooling — what could be wrong? Could be low gas, faulty thermostat, dirty coils, or compressor issue. Our technician diagnoses the exact cause.",
      "Why is there water on the floor? Usually a clogged defrost drain. Our technician clears it.",

      "Final takeaway",
      "Refrigerator repair in Bengaluru is straightforward with the right technician. Understanding common faults — not cooling, frost buildup, water leakage, compressor noise, door seal damage, over-freezing, not starting — helps you describe the problem accurately.",
      "With genuine spare parts and quality assured repair, your fridge can be back to full cooling. Clean the condenser coils twice a year and check the door seal regularly to prevent most faults.",
      "Call us for same-day refrigerator repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
  {
    slug: "water-filter-ro-repair-bengaluru-complete-guide",
    title: "Water Filter & RO Repair in Bengaluru — Complete Purifier Guide 2026",
    excerpt:
      "RO not purifying, low flow, leakage, bad taste, UV lamp, membrane replacement? Complete guide for Kent, Aquaguard, Pureit, Livpure water purifier repair across 84+ Bengaluru neighbourhoods.",
    category: "Water Filter",
    date: "2026-06-20",
    readTime: "11 min read",
    image: "/blog/water-filter-maintenance.png",
    content: [
      "Safe drinking water is non-negotiable. Bengaluru's water quality varies by area — hard borewell water in Whitefield, softer Cauvery water in Indiranagar. Your water purifier works harder here than in most cities. This guide breaks down every common water filter and RO fault.",
      "Water filter and RO purifier repair in Bengaluru covers all brands — Kent, Aquaguard, Pureit, Livpure, Blue Mount, Nasaka and more. RO, UV, UF, and combined RO+UV+UF systems. This content is intended for Bengaluru residents who want to understand what's wrong with their water purifier.",

      "Why Water Purifier Faults Happen",
      "Water purifiers fail due to clogged filters, worn membranes, pump failure, valve malfunction, and electrical faults. Bengaluru's hard water accelerates filter and membrane wear.",
      "The most common causes are hard water scaling (in areas with borewell water), sediment in the supply (clogging pre-filters and inlet valves), voltage fluctuations (damaging the PCB and pump), and natural aging of the RO membrane.",

      "1. RO Not Purifying — Membrane, Pre-Filter, or UV Lamp",
      "If your RO is not purifying water properly, the TDS reading will be higher than normal. The water may taste different or look cloudy. The cause could be a clogged RO membrane, a faulty pre-filter, a defective UV lamp, or a malfunctioning solenoid valve.",
      "The RO membrane is the core of the purifier. It removes dissolved solids, heavy metals, and impurities. Over time, the membrane gets clogged with scale and sediment. A failing membrane lets impurities through. Our technician tests the membrane's rejection rate and replaces it if needed.",
      "Pre-filters (sediment filter and carbon filter) sit before the RO membrane. They catch sediment and chlorine. If clogged, water flow to the membrane drops, reducing purification. Our technician replaces the pre-filter set.",
      "The UV lamp kills bacteria and viruses with ultraviolet light. A burnt UV lamp has no visible sign — the water looks clean but isn't disinfected. Our technician tests the lamp and ballast and replaces the lamp.",
      "The solenoid valve controls water flow through the purifier. A faulty valve causes water to flow continuously or not at all. Our technician tests and replaces the valve.",

      "2. Low Water Flow — Blocked Cartridges or Faulty Pump",
      "If water is flowing slowly from your purifier, the cause is blocked filter cartridges, a clogged RO membrane, or a faulty booster pump.",
      "Filter cartridges (pre-filter, carbon, post-carbon, sediment) accumulate sediment and debris over time. As they clog, water flow decreases. Our technician replaces the cartridge set.",
      "A clogged RO membrane restricts water flow. As the membrane ages and scales up, less water passes through. Our technician checks the membrane and replaces it if the flow rate is below specification.",
      "The booster pump maintains the pressure needed to push water through the RO membrane. Without adequate pressure, purification drops. Our technician tests the pump's pressure output and replaces it if faulty.",

      "3. Water Leakage — Loose Fittings or Cracked Housing",
      "Water leaking from the purifier is caused by loose fittings, a cracked filter housing, a damaged O-ring, or a burst tube.",
      "Our technician inspects every connection, fitting, and housing. We tighten loose fittings, replace cracked housings, and install new O-rings. We also check all internal tubes for cracks or pinholes.",

      "4. Bad Taste or Smell — Carbon Filter or Bacterial Buildup",
      "If your purified water tastes or smells bad, the carbon filter is saturated or there's bacterial buildup in the storage tank.",
      "The carbon filter removes chlorine, bad taste, and odour. When saturated, it stops working. Our technician replaces the carbon filter.",
      "Bacterial buildup in the storage tank causes a foul smell, especially during Bengaluru's humid monsoon. Our technician sanitises the tank and the entire system.",

      "5. RO Membrane Replacement — When and Why",
      "The RO membrane needs replacement every 1-2 years depending on water quality and usage. Bengaluru's hard borewell water (TDS 300-500 ppm in some areas) shortens membrane life.",
      "Signs your membrane needs replacement: TDS reading climbing, water taste changing, flow rate dropping, or the purifier running longer than usual.",
      "Our technician checks the membrane's rejection rate using a TDS meter. If the rejection rate is below 80%, we recommend replacement. We use genuine membranes from Kent, Aquaguard, Pureit, and Livpure.",

      "6. UV Lamp Replacement",
      "The UV lamp needs annual replacement. UV lamp life is 8,000-10,000 hours (approximately 1 year of use). A burnt lamp doesn't disinfect the water.",
      "Our technician tests the lamp and ballast, and replaces the lamp with a genuine spare. We also clean the quartz sleeve that covers the UV lamp — a dirty sleeve blocks UV light.",

      "7. Auto Shut-Off Issues — Float Valve or Sensor",
      "If the tank overflows or the purifier doesn't turn on, the float valve or water level sensor is faulty.",
      "The float valve shuts off water when the tank is full. A stuck float valve causes overflow. Our technician cleans or replaces the float valve.",
      "The water level sensor (in electronic purifiers) detects the water level and controls the pump. A faulty sensor causes the pump to run continuously or not at all. Our technician replaces the sensor.",

      "How Our Water Filter Repair Process Works",
      "Step 1: Tell us the symptom. Share the brand and type (RO, UV, UF, combined).",
      "Step 2: Free diagnosis. Our technician tests TDS, water flow, membrane, pump, UV lamp, and valves.",
      "Step 3: Transparent quote. We share a clear quote. You approve before any work.",
      "Step 4: Repair at home. Most repairs take 30-60 minutes. Genuine spare parts.",
      "Step 5: Quality assured. All repairs are quality assured.",

      "Brands We Service in Bengaluru",
      "Kent water purifier repair in Bengaluru — RO, UV, and combined systems. We carry genuine Kent membranes, UV lamps, filters, pumps, and valves.",
      "Aquaguard water purifier repair in Bengaluru — RO, UV, and combined systems.",
      "Pureit water purifier repair in Bengaluru — RO and UV systems.",
      "Livpure water purifier repair in Bengaluru — RO and UV systems.",
      "Blue Mount water purifier repair in Bengaluru — RO systems.",
      "Nasaka water purifier repair in Bengaluru — RO and UV systems.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, water purifier repair is essential due to the city's varying water quality. Hard borewell water in Whitefield, Marathahalli, and HSR Layout causes faster membrane and filter clogging. Areas with Cauvery water (Indiranagar, Jayanagar) have softer water but still need regular maintenance.",
      "From Indiranagar to Whitefield, our verified technicians reach every corner. Same-day slots across all 84+ neighbourhoods.",

      "Water filter repair near me in Bengaluru",
      "Looking for water filter repair near you? We serve all of Bengaluru:",
      "Water filter repair in Indiranagar. Water filter repair in Koramangala. Water filter repair in Whitefield. Water filter repair in HSR Layout. Water filter repair in Jayanagar. Water filter repair in Marathahalli. Water filter repair in BTM Layout. Water filter repair in Electronic City. Water filter repair in Hebbal. Water filter repair in Malleswaram. Water filter repair in Rajajinagar. Water filter repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — Water Filter Repair in Bengaluru",
      "When you search for water filter or RO repair in Bengaluru, three names will come up — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your water purifier.",
      "Urban Company is a national home services platform with a clean app. Their water purifier repair covers multiple brands. However, their technicians are generalists handling many appliance types — which means they may not carry water filter-specific spare parts like RO membranes, UV lamps, booster pumps, solenoid valves, or filter cartridges on the first visit. RO membrane replacement requires a TDS meter to verify rejection rate, and UV lamp replacement requires ballast testing — not all generalist technicians carry this equipment. Their pricing includes a platform visit fee, and same-day slots are often limited.",
      "Local Ramu is a Bengaluru-based repair provider. Being local, they understand the city's water quality challenges — hard borewell water in Whitefield and Marathahalli, softer Cauvery water in Indiranagar. However, their technician pool is smaller, which means longer wait times during peak hours. They also may not carry genuine brand-specific spare parts for all six brands we service — Kent, Aquaguard, Pureit, Livpure, Blue Mount, and Nasaka. RO membrane and UV lamp replacement requires specialised knowledge that generalist technicians may not have.",
      "Urban Service Company is Bengaluru-born, water purifier-specialist, and carries genuine spare parts on every visit. Our technicians are trained specifically on water filter diagnostics — TDS meter testing, RO membrane rejection rate verification, UV lamp and ballast testing, booster pump pressure testing, solenoid valve inspection, filter cartridge replacement, float valve and water level sensor repair, and full system sanitisation. Same-day slots are available across all 84+ neighbourhoods. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want a water purifier specialist with genuine parts, TDS meter testing, and same-day service across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — Water filter repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for water filter repair? Urban Service Company is water purifier-specialist with genuine brand-specific parts and TDS testing on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts. We offer same-day slots, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for water filter repair? Both are Bengaluru-local. Urban Service Company specialises in water purifier repair with trained technicians, genuine parts for all six major brands, and TDS meter testing. Local Ramu is a generalist with a smaller technician pool. For RO-specific faults like membrane failure or UV lamp burnout, a specialist is recommended.",
      "Do you repair all water purifier brands? Yes. Kent, Aquaguard, Pureit, Livpure, Blue Mount, Nasaka — RO, UV, UF, and combined systems.",
      "How fast can a technician reach my home? Same-day slots. Typically within 45 to 60 minutes.",
      "Is diagnosis free? Yes. Free when you proceed with the repair.",
      "Do you carry genuine spare parts? Yes. RO membranes, UV lamps, filters, pumps, valves, and sensors.",
      "How often should I replace the RO membrane? Every 1-2 years depending on water quality and usage.",
      "Why does my water taste bad? The carbon filter may be saturated or there's bacterial buildup. Our technician replaces the filter and sanitises the system.",

      "Final takeaway",
      "Water filter and RO repair in Bengaluru is critical for safe drinking water. Understanding common faults — not purifying, low flow, leakage, bad taste, UV lamp failure, membrane aging, pump failure, auto shut-off issues — helps you describe the problem accurately.",
      "With genuine spare parts and quality assured repair, your water purifier can be back to full performance. Replace pre-filters every 6 months, the RO membrane every 1-2 years, and the UV lamp annually.",
      "Call us for same-day water filter repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
  {
    slug: "kitchen-chimney-repair-bengaluru-complete-guide",
    title: "Kitchen Chimney Repair in Bengaluru — Complete Service Guide 2026",
    excerpt:
      "Chimney not sucking smoke, noisy motor, low suction, touch panel dead, filter cleaning? Complete guide for Faber, Elica, Bosch, Hindware, Glen, Kaff chimney repair across 84+ Bengaluru neighbourhoods.",
    category: "Chimney",
    date: "2026-06-15",
    readTime: "11 min read",
    image: "/blog/chimney-cleaning.png",
    content: [
      "A kitchen chimney keeps your kitchen smoke-free, odour-free, and oil-free. When it stops working, cooking becomes a smokey, smelly ordeal. This guide breaks down every common kitchen chimney fault.",
      "Kitchen chimney repair in Bengaluru covers all brands — Faber, Elica, Bosch, Hindware, Glen, Kaff and Crompton. Wall-mounted, island, and decorative chimneys. This content is intended for Bengaluru residents who want to understand what's wrong with their chimney before calling a technician.",

      "Why Chimney Faults Happen",
      "Kitchen chimneys fail due to oil buildup, motor wear, filter clogging, electrical faults, and lack of regular cleaning. Indian cooking — with its heavy use of oil, spices, and high-heat methods — is particularly hard on chimneys.",
      "The most common causes are oil-soaked filters (reducing suction and straining the motor), lack of professional deep cleaning (oil accumulates on the motor, blower, and duct), voltage fluctuations (damaging the motor and touch panel), and natural wear of the motor bearings.",

      "1. Chimney Not Sucking Smoke — Clogged Filter or Faulty Motor",
      "If your chimney is running but smoke isn't being extracted, the cause is a clogged filter, a faulty suction motor, a blocked duct, or a defective blower.",
      "Clogged baffle filters are the most common cause. Oil and food particles accumulate on the filters, blocking airflow. Our technician removes, deep-cleans, and reinstalls the filters. If the filters are damaged, we replace them.",
      "A faulty suction motor doesn't generate enough suction. Motor failure is caused by bearing wear, capacitor failure, or winding burnout. Our technician tests the motor's electrical readings and replaces it if faulty.",
      "A blocked duct restricts airflow between the chimney and the exterior. Birds' nests, debris, or oil buildup in the duct cause blockages. Our technician inspects and clears the duct.",
      "A defective blower (the fan assembly that moves air) can be damaged or jammed. Our technician inspects the blower and replaces it if needed.",

      "2. Excessive Noise — Motor Bearing, Blower, or Fan Blade",
      "A noisy chimney — grinding, rattling, or humming — indicates a mechanical problem.",
      "Worn motor bearings cause a grinding or humming sound. Over time, oil and heat degrade the bearings. Our technician replaces the bearings or the entire motor.",
      "A loose blower causes a rattling sound. The blower wheel can come loose from the motor shaft. Our technician tightens or replaces the blower.",
      "A damaged fan blade causes vibration and noise. A bent or cracked blade unbalances the system. Our technician replaces the fan blade.",
      "Oil buildup on the motor and blower adds weight and imbalance, causing noise even with good bearings. Our technician deep-cleans the motor and blower assembly.",

      "3. Low Suction Power — Dirty Filters or Weak Motor",
      "If the chimney runs but doesn't pull smoke effectively, suction power has dropped. The cause is dirty filters, oil buildup on the motor and blower, or a weakening motor.",
      "Our technician deep-cleans the filters, motor, blower, and duct. If suction is still low after cleaning, we test the motor and capacitor. A weak motor or a faulty capacitor reduces suction. We replace the faulty component.",

      "4. LED Light Not Working — Faulty Light, Switch, or Wiring",
      "If the chimney's LED light doesn't turn on, the cause is a faulty LED light unit, a broken switch, or a wiring issue.",
      "Our technician tests the light unit, switch, and wiring. We replace the LED light with a genuine spare. Most chimneys use standard LED lights, but some brands use proprietary units.",

      "5. Motor Failure — Burnt Motor, Capacitor, or Bearing",
      "Motor failure is the most serious chimney fault. The motor drives the blower that creates suction. A failed motor means the chimney doesn't work at all.",
      "A burnt motor is caused by overheating (from oil buildup insulating the motor), voltage fluctuations, or age. Our technician tests the motor's windings and replaces it with a genuine spare.",
      "Capacitor failure prevents the motor from starting. The capacitor provides the energy boost needed to start the motor. Our technician tests and replaces the capacitor.",
      "Bearing wear causes the motor to run noisily and eventually seize. Our technician replaces the bearings or the entire motor.",

      "6. Touch Panel Not Working — Control Board or Ribbon Cable",
      "If the chimney's touch panel or buttons don't respond, the control board or ribbon cable is faulty.",
      "The touch control board processes your inputs. A faulty board doesn't register touches. Our technician tests the board and replaces it with a genuine spare.",
      "The ribbon cable connects the touch panel to the control board. A damaged or loose cable causes intermittent or no response. Our technician replaces the cable.",

      "7. Filter Cleaning and Deep Chimney Service",
      "Regular cleaning is the single most important maintenance step for your chimney. Oil-soaked filters reduce suction, strain the motor, and cause odours.",
      "Baffle filter cleaning: Our technician removes the baffle filters, soaks them in a degreasing solution, scrubs them clean, and reinstalls them. We recommend this every 2 weeks for home use.",
      "Deep chimney service: Our technician dismantles the chimney, deep-cleans the motor, blower, duct, and internal components. This removes oil buildup that you can't reach. We recommend this every 3 months.",
      "Carbon filter replacement: For filterless (recirculating) chimneys, carbon filters absorb odours. These should be replaced annually. Our technician replaces them with genuine spares.",

      "How Our Chimney Repair Process Works",
      "Step 1: Tell us the symptom. Share the brand and type (wall-mounted, island, decorative).",
      "Step 2: Free diagnosis. Our technician inspects the chimney and identifies the fault.",
      "Step 3: Transparent quote. We share a clear quote. You approve before any work.",
      "Step 4: Repair at home. Most repairs take 30-60 minutes. Genuine spare parts.",
      "Step 5: Quality assured. All repairs are quality assured.",

      "Brands We Service in Bengaluru",
      "Faber chimney repair in Bengaluru — wall-mounted, island, and decorative. We carry genuine Faber motors, filters, blowers, control panels, and capacitors.",
      "Elica chimney repair in Bengaluru — all models.",
      "Bosch chimney repair in Bengaluru — all models.",
      "Hindware chimney repair in Bengaluru — all models.",
      "Glen chimney repair in Bengaluru — all models.",
      "Kaff chimney repair in Bengaluru — all models.",
      "Crompton chimney repair in Bengaluru — all models.",

      "How's the repair scene in Bengaluru?",
      "In Bengaluru, kitchen chimney repair is growing as more homes install chimneys for smoke-free cooking. Indian cooking — with tempering (tadka), deep-frying, and high-heat roasting — produces heavy oil and smoke that strains chimneys.",
      "From Indiranagar to Whitefield, our verified technicians reach every corner. Same-day slots across all 84+ neighbourhoods.",

      "Chimney repair near me in Bengaluru",
      "Looking for chimney repair near you? We serve all of Bengaluru:",
      "Chimney repair in Indiranagar. Chimney repair in Koramangala. Chimney repair in Whitefield. Chimney repair in HSR Layout. Chimney repair in Jayanagar. Chimney repair in Marathahalli. Chimney repair in BTM Layout. Chimney repair in Electronic City. Chimney repair in Hebbal. Chimney repair in Malleswaram. Chimney repair in Rajajinagar. Chimney repair in Yelahanka.",

      "Urban Service Company vs Urban Company and Local Ramu — Chimney Repair in Bengaluru",
      "When you search for kitchen chimney repair in Bengaluru, three names will appear — Urban Service Company, Urban Company, and Local Ramu. Here's an honest comparison to help you choose the right service for your chimney.",
      "Urban Company is a national home services platform with a clean app. Their chimney repair covers multiple brands. However, their technicians are generalists handling many appliance types — which means they may not carry chimney-specific spare parts like suction motors, blowers, control panels, capacitors, or LED lights on the first visit. Chimney motor replacement requires electrical winding testing, and touch panel diagnosis requires control board and ribbon cable inspection — not all generalist technicians have experience with chimney internals. Their pricing includes a platform visit fee, and same-day slots during weekends (when most Bengaluru residents cook heavily) are often fully booked.",
      "Local Ramu is a Bengaluru-based repair provider. Being local, they understand Indian cooking patterns — tempering (tadka), deep-frying, and high-heat roasting that produce heavy oil and smoke. However, their technician pool is smaller, which means longer wait times during peak hours. They also may not carry genuine brand-specific spare parts for all seven brands we service — Faber, Elica, Bosch, Hindware, Glen, Kaff, and Crompton. Deep chimney service (full dismantling, motor and blower cleaning, duct clearing) requires specialised tools and experience that generalist technicians may not have.",
      "Urban Service Company is Bengaluru-born, chimney-specialist, and carries genuine spare parts on every visit. Our technicians are trained specifically on chimney diagnostics — suction motor testing, blower inspection, baffle filter deep cleaning, touch control board and ribbon cable diagnosis, capacitor replacement, LED light repair, and full deep chimney service with dismantling. Same-day slots are available across all 84+ neighbourhoods. No platform fee. Free diagnosis. Genuine parts. Quality assured.",
      "The choice depends on your priority. If you want a national app-based platform, Urban Company is an option. If you want a local generalist, Local Ramu is an option. If you want a chimney specialist with genuine parts, deep service expertise, and same-day service across Bengaluru — Urban Service Company is the right choice.",

      "FAQs — Chimney repair in Bengaluru",
      "How does Urban Service Company compare to Urban Company for chimney repair? Urban Service Company is chimney-specialist with genuine brand-specific parts on every visit. Urban Company is a national platform with generalist technicians who may need revisits for parts. We offer same-day slots, free diagnosis, and no platform fee.",
      "Is Urban Service Company better than Local Ramu for chimney repair? Both are Bengaluru-local. Urban Service Company specialises in chimney repair with trained technicians and genuine parts for all seven major brands. Local Ramu is a generalist with a smaller technician pool. For chimney-specific faults like motor failure or touch panel issues, a specialist is recommended.",
      "Do you repair all chimney brands? Yes. Faber, Elica, Bosch, Hindware, Glen, Kaff, Crompton — wall-mounted, island, and decorative.",
      "How fast can a technician reach my home? Same-day slots. Typically within 45 to 60 minutes.",
      "Is diagnosis free? Yes. Free when you proceed with the repair.",
      "Do you carry genuine spare parts? Yes. Motors, filters, blowers, control panels, capacitors, and LED lights.",
      "How often should I clean my chimney filters? Every 2 weeks for baffle filters. Professional deep clean every 3 months.",
      "My chimney is noisy — what's wrong? Likely worn motor bearings or loose blower. Our technician identifies the source.",
      "My chimney touch panel is not working — can you fix it? Yes. Usually a faulty control board or ribbon cable. We replace it.",

      "Final takeaway",
      "Kitchen chimney repair in Bengaluru keeps your kitchen smoke-free and your family healthy. Understanding common faults — not sucking smoke, noise, low suction, LED light, motor failure, touch panel, filter cleaning — helps you describe the problem accurately.",
      "With genuine spare parts and quality assured repair, your chimney can be back to full suction. Clean baffle filters every 2 weeks and get a professional deep clean every 3 months.",
      "Call us for same-day chimney repair across 84+ neighbourhoods in Bengaluru. Free diagnosis. Genuine parts. Quality assured.",
    ],
  },
];
